
---
apiVersion: v1
kind: Pod
metadata:
   name: postgres-pod
   labels:
     author: chiru
     type: db
spec:
  containers:
    - name: postgres1
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: chiru

    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 9090
...


