
---
apiVersion: v1
kind: ReplicationController
metadata:
   name: replic-control
   labels:
      author: chiru
      type: web-server
spec:
   replicas: 2
   template:
      metadata:
        name: replica-pod
        labels:
          author: chiru
          type: web-server1
      spec:
        containers:
          - name: httpd-cont
            image: httpd
            ports:
              - containerPort: 80
                hostPort: 8080

...

