
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
   author: chiru
   type: webserver
spec:
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
     nodePort: 31000
  selector:
   author: chiru
   type: webserver
... 

